from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path


ROOT = Path(r"C:\Users\conra\Desktop\dighumproject")
OUTPUT = ROOT / "konbaung_node_identity_regex_refinement_20260725"
POOL = OUTPUT / "regex_candidate_pool.jsonl"


def pair(left: str, right: str) -> str:
    return f"{left}|{right}"


# All pairs generated by these tightly constrained rules were individually
# inspected. Their matched aliases differ only in formatting or title order.
ACCEPT_COMPLETE_RULES = {
    "format_exact",
    "compact_exact",
    "title_order_template",
}

# Regex similarity only surfaces candidates. These pairs were removed after
# checking sentence evidence: they are opposites, homonyms, different
# office-holders/royals/monks, or similarly spelled but distinct referents.
# This override applies even when a broad rule above would otherwise accept.
REJECT_CONTEXT_CONFLICT = {
    # Title/order matches resolving to different people or office-holders.
    pair("N-1233", "N-10970"),
    pair("N-2262", "N-6362"),
    pair("N-0363", "N-2732"),
    pair("N-0878", "N-2872"),
    pair("N-8522", "N-10615"),
    pair("N-2728", "N-12792"),
    pair("N-8533", "N-15291"),
    pair("N-1402", "N-4463"),
    pair("N-1402", "N-15756"),
    pair("N-0377", "N-2757"),
    pair("N-0907", "N-3716"),
    pair("N-2954", "N-9556"),
    pair("N-3330", "N-3818"),
    pair("N-1592", "N-11143"),
    pair("N-0130", "N-0732"),
    pair("N-0983", "N-8524"),
    pair("N-5129", "N-11455"),
    pair("N-0132", "N-1884"),
    pair("N-12959", "N-13001"),
    pair("N-1755", "N-6120"),
    pair("N-0530", "N-1970"),
    pair("N-4129", "N-14534"),
    pair("N-4463", "N-15756"),
    pair("N-0578", "N-3897"),
    pair("N-2065", "N-3827"),
    # Token-order matches whose contexts identify different referents.
    pair("N-10616", "N-14864"),
    pair("N-0415", "N-2876"),
    pair("N-3796", "N-4270"),
    pair("N-2049", "N-17674"),
    # One-character/transliteration matches rejected by context.
    pair("N-2180", "N-16485"),
    pair("N-2195", "N-2993"),
    pair("N-0637", "N-4543"),
    pair("N-1497", "N-9852"),
    pair("N-3121", "N-10153"),
    pair("N-3122", "N-10181"),
    pair("N-0942", "N-10379"),
    pair("N-3191", "N-10530"),
    pair("N-3226", "N-11068"),
    pair("N-1553", "N-10921"),
    pair("N-5108", "N-10803"),
    pair("N-5119", "N-11100"),
    pair("N-3397", "N-11296"),
    pair("N-3446", "N-3455"),
    pair("N-0995", "N-6130"),
    pair("N-11818", "N-11821"),
    pair("N-11980", "N-12127"),
    pair("N-1011", "N-11976"),
    pair("N-1665", "N-11983"),
    pair("N-12196", "N-12201"),
    pair("N-3600", "N-3601"),
    pair("N-1687", "N-12050"),
    pair("N-12455", "N-12457"),
    pair("N-1700", "N-12471"),
    pair("N-3685", "N-6425"),
    pair("N-0153", "N-1052"),
    pair("N-1776", "N-3827"),
    pair("N-13493", "N-13511"),
    pair("N-14278", "N-14601"),
    pair("N-4151", "N-16467"),
    pair("N-1900", "N-4195"),
    pair("N-4265", "N-14927"),
    pair("N-1093", "N-14448"),
    pair("N-1933", "N-4299"),
    pair("N-15097", "N-15119"),
    pair("N-15157", "N-15230"),
    pair("N-15166", "N-15238"),
    pair("N-1116", "N-15215"),
    pair("N-15273", "N-17261"),
    pair("N-1961", "N-15553"),
    pair("N-15717", "N-15747"),
    pair("N-0236", "N-4511"),
    pair("N-1136", "N-4511"),
    pair("N-4577", "N-16155"),
    pair("N-2018", "N-8887"),
    pair("N-5310", "N-16527"),
    pair("N-2029", "N-16522"),
    pair("N-1161", "N-16535"),
    # A singular/plural royal epithet used for different kings.
    pair("N-0216", "N-1508"),
}

ACCEPT_DIACRITIC = {
    pair("N-3406", "N-11328"),
    pair("N-15194", "N-15195"),
}

ACCEPT_TOKEN_ORDER = {
    pair("N-6391", "N-12334"),
    pair("N-1288", "N-1608"),
    pair("N-2428", "N-18302"),
    pair("N-7305", "N-14033"),
    pair("N-0611", "N-13768"),
    pair("N-7950", "N-17565"),
    pair("N-2605", "N-7034"),
    pair("N-2607", "N-7629"),
    pair("N-2715", "N-13962"),
    pair("N-9210", "N-15775"),
    pair("N-10616", "N-14864"),
    pair("N-1548", "N-1578"),
    pair("N-1551", "N-7388"),
    pair("N-1568", "N-6242"),
    pair("N-1578", "N-17471"),
    pair("N-0968", "N-2778"),
    pair("N-3322", "N-11034"),
    pair("N-1591", "N-11158"),
    pair("N-11216", "N-14704"),
    pair("N-0679", "N-12426"),
    pair("N-4904", "N-12428"),
    pair("N-11459", "N-11460"),
    pair("N-12316", "N-15411"),
    pair("N-12400", "N-14700"),
    pair("N-0521", "N-0705"),
    pair("N-5165", "N-7231"),
    pair("N-3736", "N-12637"),
    pair("N-3776", "N-10807"),
    pair("N-0415", "N-2876"),
    pair("N-3796", "N-4270"),
    pair("N-5183", "N-7303"),
    pair("N-3808", "N-4050"),
    pair("N-13059", "N-14146"),
    pair("N-3902", "N-13055"),
    pair("N-3965", "N-4101"),
    pair("N-14150", "N-18620"),
    pair("N-0420", "N-12584"),
    pair("N-4132", "N-9712"),
    pair("N-14642", "N-18195"),
    pair("N-15084", "N-15833"),
    pair("N-1121", "N-5246"),
    pair("N-15460", "N-16714"),
    pair("N-5276", "N-13632"),
    pair("N-15620", "N-18722"),
    pair("N-16713", "N-18746"),
    pair("N-2049", "N-17674"),
}

ACCEPT_CONJUNCTION = {
    pair("N-2793", "N-8862"),
    pair("N-3444", "N-11458"),
    pair("N-3900", "N-3902"),
    pair("N-13920", "N-18467"),
}

ACCEPT_SINGULAR = {
    pair("N-6017", "N-17269"),
    pair("N-2538", "N-7572"),
    pair("N-2765", "N-8679"),
    pair("N-1504", "N-9962"),
    pair("N-0216", "N-1508"),
    pair("N-5076", "N-18013"),
    pair("N-3317", "N-3324"),
    pair("N-11183", "N-11227"),
    pair("N-3643", "N-12401"),
    pair("N-5194", "N-18362"),
    pair("N-3900", "N-13348"),
    pair("N-3946", "N-13517"),
    pair("N-0715", "N-3972"),
    pair("N-5207", "N-13361"),
    pair("N-0418", "N-4005"),
    pair("N-1824", "N-18566"),
    pair("N-0540", "N-1840"),
    pair("N-1080", "N-1836"),
    pair("N-4207", "N-14541"),
    pair("N-1936", "N-15025"),
    pair("N-4542", "N-18807"),
}

ACCEPT_SINGULAR_ORDER = {
    pair("N-7070", "N-12739"),
}

ACCEPT_PLACE_SUFFIX = {
    pair("N-4936", "N-6122"),
    pair("N-2312", "N-2314"),
    pair("N-2468", "N-4970"),
    pair("N-7497", "N-7499"),
    pair("N-0214", "N-4889"),
    pair("N-1454", "N-9239"),
    pair("N-5053", "N-9560"),
    pair("N-0488", "N-9711"),
    pair("N-0217", "N-1614"),
    pair("N-3345", "N-11077"),
    pair("N-3425", "N-11404"),
    pair("N-0984", "N-11447"),
    pair("N-3719", "N-5169"),
    pair("N-0525", "N-12859"),
    pair("N-3886", "N-13293"),
    pair("N-4161", "N-14478"),
    pair("N-2076", "N-17152"),
}

ACCEPT_ONE_CHAR = {
    pair("N-2180", "N-16485"),
    pair("N-2190", "N-6052"),
    pair("N-2195", "N-2993"),
    pair("N-2248", "N-6303"),
    pair("N-6306", "N-6310"),
    pair("N-0805", "N-1777"),
    pair("N-2285", "N-6484"),
    pair("N-1251", "N-6488"),
    pair("N-2287", "N-6496"),
    pair("N-6593", "N-6596"),
    pair("N-1301", "N-7112"),
    pair("N-1310", "N-17457"),
    pair("N-7421", "N-7433"),
    pair("N-0848", "N-7464"),
    pair("N-0847", "N-1331"),
    pair("N-7569", "N-7632"),
    pair("N-2551", "N-7663"),
    pair("N-7704", "N-7706"),
    pair("N-0997", "N-8749"),
    pair("N-8783", "N-8869"),
    pair("N-0887", "N-8812"),
    pair("N-8798", "N-9706"),
    pair("N-0637", "N-4543"),
    pair("N-2795", "N-2796"),
    pair("N-0900", "N-2856"),
    pair("N-0901", "N-9186"),
    pair("N-2868", "N-9215"),
    pair("N-5046", "N-9385"),
    pair("N-9367", "N-9399"),
    pair("N-5055", "N-9527"),
    pair("N-2970", "N-9522"),
    pair("N-1497", "N-9852"),
    pair("N-3047", "N-9918"),
    pair("N-3048", "N-9929"),
    pair("N-1505", "N-9975"),
    pair("N-10055", "N-10056"),
    pair("N-10169", "N-10299"),
    pair("N-3107", "N-10196"),
    pair("N-10246", "N-10281"),
    pair("N-0662", "N-10254"),
    pair("N-3121", "N-10153"),
    pair("N-3122", "N-10181"),
    pair("N-0942", "N-10379"),
    pair("N-3191", "N-10530"),
    pair("N-3226", "N-11068"),
    pair("N-1553", "N-10921"),
    pair("N-10743", "N-10788"),
    pair("N-5105", "N-10752"),
    pair("N-3358", "N-11104"),
    pair("N-3244", "N-3268"),
    pair("N-10791", "N-11070"),
    pair("N-10803", "N-11077"),
    pair("N-3255", "N-10859"),
    pair("N-10843", "N-10860"),
    pair("N-1567", "N-10733"),
    pair("N-10983", "N-11028"),
    pair("N-1584", "N-10750"),
    pair("N-5108", "N-10803"),
    pair("N-0970", "N-3348"),
    pair("N-5119", "N-11100"),
    pair("N-0676", "N-3369"),
    pair("N-3397", "N-11296"),
    pair("N-3433", "N-11472"),
    pair("N-3446", "N-3455"),
    pair("N-11549", "N-11557"),
    pair("N-11602", "N-11604"),
    pair("N-3471", "N-11619"),
    pair("N-0995", "N-6130"),
    pair("N-3506", "N-11791"),
    pair("N-11818", "N-11821"),
    pair("N-1011", "N-11976"),
    pair("N-1665", "N-11983"),
    pair("N-11980", "N-12127"),
    pair("N-12196", "N-12201"),
    pair("N-3600", "N-3601"),
    pair("N-1687", "N-12050"),
    pair("N-1689", "N-12249"),
    pair("N-1022", "N-18185"),
    pair("N-12455", "N-12457"),
    pair("N-1700", "N-12471"),
    pair("N-0699", "N-0857"),
    pair("N-3685", "N-6425"),
    pair("N-0153", "N-1052"),
    pair("N-3719", "N-12694"),
    pair("N-1718", "N-12695"),
    pair("N-3728", "N-12750"),
    pair("N-1040", "N-1733"),
    pair("N-0171", "N-2992"),
    pair("N-1776", "N-3827"),
    pair("N-0339", "N-13445"),
    pair("N-13493", "N-13511"),
    pair("N-14278", "N-14601"),
    pair("N-1093", "N-14448"),
    pair("N-14327", "N-14439"),
    pair("N-4138", "N-4140"),
    pair("N-4151", "N-16467"),
    pair("N-1900", "N-4195"),
    pair("N-4240", "N-14722"),
    pair("N-4265", "N-14927"),
    pair("N-14828", "N-14850"),
    pair("N-4275", "N-14863"),
    pair("N-1109", "N-14875"),
    pair("N-1928", "N-4291"),
    pair("N-1929", "N-14920"),
    pair("N-1933", "N-4299"),
    pair("N-15097", "N-15119"),
    pair("N-5265", "N-15096"),
    pair("N-15157", "N-15230"),
    pair("N-15166", "N-15238"),
    pair("N-1116", "N-15215"),
    pair("N-15185", "N-15192"),
    pair("N-5270", "N-15163"),
    pair("N-15272", "N-17260"),
    pair("N-15273", "N-17261"),
    pair("N-1961", "N-15553"),
    pair("N-4450", "N-8878"),
    pair("N-4452", "N-4466"),
    pair("N-4457", "N-15778"),
    pair("N-15717", "N-15747"),
    pair("N-1972", "N-3791"),
    pair("N-15803", "N-15804"),
    pair("N-0236", "N-4511"),
    pair("N-1136", "N-4511"),
    pair("N-0560", "N-1984"),
    pair("N-1140", "N-4509"),
    pair("N-0184", "N-15859"),
    pair("N-4530", "N-15899"),
    pair("N-4531", "N-15939"),
    pair("N-4536", "N-15979"),
    pair("N-4577", "N-16155"),
    pair("N-2017", "N-4644"),
    pair("N-2018", "N-8887"),
    pair("N-5310", "N-16527"),
    pair("N-2029", "N-16522"),
    pair("N-4886", "N-16510"),
    pair("N-1161", "N-16535"),
    pair("N-4735", "N-16594"),
    pair("N-4840", "N-17136"),
    pair("N-4848", "N-17121"),
    pair("N-17135", "N-18997"),
}

EXPLICIT_ACCEPT = (
    ACCEPT_DIACRITIC
    | ACCEPT_TOKEN_ORDER
    | ACCEPT_CONJUNCTION
    | ACCEPT_SINGULAR
    | ACCEPT_SINGULAR_ORDER
    | ACCEPT_PLACE_SUFFIX
    | ACCEPT_ONE_CHAR
)

REASONS = {
    "format_exact": "Same normalized text after case, punctuation, separator, and whitespace normalization.",
    "compact_exact": "Same alphanumeric text after formatting normalization.",
    "title_order_template": "Same title/place construction with only 'of' or title-word order changed.",
    "diacritic_exact": "Same distinctive name after removing scholarly diacritics.",
    "token_order_exact": "Same referent tokens reordered without changing membership.",
    "conjunction_format_exact": "Same verified group with conjunction formatting changed.",
    "singular_format_exact": "Same verified concept or collective with singular/plural formatting changed.",
    "singular_token_order_exact": "Same verified concept with singular/plural and token order changed.",
    "place_suffix_template": "Same verified place with bare, town, or city wording.",
    "one_char_edit": "Same verified distinctive referent with a one-character transliteration or transcription variant.",
}


def read_pool() -> list[dict]:
    with POOL.open("r", encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def main() -> None:
    rows = read_pool()
    pool_by_pair = {pair(row["leftClusterId"], row["rightClusterId"]): row for row in rows}
    missing = sorted(EXPLICIT_ACCEPT - set(pool_by_pair))
    if missing:
        raise RuntimeError(f"Accepted pairs missing from regenerated pool: {missing}")
    missing_rejects = sorted(REJECT_CONTEXT_CONFLICT - set(pool_by_pair))
    if missing_rejects:
        raise RuntimeError(
            f"Context-conflict pairs missing from regenerated pool: {missing_rejects}"
        )

    decisions: list[dict] = []
    accepted: list[dict] = []
    for row in rows:
        key = pair(row["leftClusterId"], row["rightClusterId"])
        surfaced_as_accept = row["primaryRule"] in ACCEPT_COMPLETE_RULES or key in EXPLICIT_ACCEPT
        is_accepted = surfaced_as_accept and key not in REJECT_CONTEXT_CONFLICT
        decision = {
            **row,
            "manualDecision": (
                "ACCEPTED_VERIFIED"
                if is_accepted
                else (
                    "EXCLUDED_CONTEXT_CONFLICT"
                    if key in REJECT_CONTEXT_CONFLICT
                    else "EXCLUDED_NOT_PROVEN"
                )
            ),
            "manualReason": (
                REASONS[row["primaryRule"]]
                if is_accepted
                else (
                    "Sentence evidence indicates distinct referents or a semantic conflict."
                    if key in REJECT_CONTEXT_CONFLICT
                    else "The regex resemblance alone did not establish exact referent identity."
                )
            ),
        }
        decisions.append(decision)
        if is_accepted:
            accepted.append(decision)

    with (OUTPUT / "regex_candidate_adjudication.jsonl").open(
        "w", encoding="utf-8", newline="\n"
    ) as handle:
        for row in decisions:
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")

    csv_rows = [
        {
            "left_cluster_id": row["leftClusterId"],
            "left_identity": row["leftCanonical"],
            "right_cluster_id": row["rightClusterId"],
            "right_identity": row["rightCanonical"],
            "rule": row["primaryRule"],
            "reason": row["manualReason"],
        }
        for row in accepted
    ]
    csv_path = OUTPUT / "regex_verified_merge_candidates.csv"
    with csv_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(csv_rows[0]))
        writer.writeheader()
        writer.writerows(csv_rows)

    clean_lines = [
        "# Manually verified regex-only merge candidates",
        "",
        f"- Candidate pool reviewed: {len(rows)}",
        f"- Retained merge candidates: {len(accepted)}",
        "- Embeddings used: 0",
        "- Source clusters modified: no",
        "",
        "Every pair below was surfaced without embeddings and retained only after "
        "checking that both sides denote the same referent or normalized concept "
        "in the available sentence evidence.",
        "",
        "Near-matches involving semantic opposites, homonyms, different title-holders, "
        "different royals or monks, and distinct places or objects were excluded.",
        "",
    ]
    for row in accepted:
        clean_lines.append(f"- {row['leftCanonical']} ↔ {row['rightCanonical']}")
    clean_path = OUTPUT / "REGEX_VERIFIED_MERGE_CANDIDATES.md"
    clean_path.write_text("\n".join(clean_lines) + "\n", encoding="utf-8")

    evidence_lines = [
        "# Evidence for manually verified regex-only candidates",
        "",
        f"- Retained merge candidates: {len(accepted)}",
        "- Embeddings used: 0",
        "",
    ]
    for row in accepted:
        evidence = row["allEvidence"][0]
        evidence_lines.extend(
            [
                f"## {row['leftCanonical']} ↔ {row['rightCanonical']}",
                "",
                f"- Rule: `{row['primaryRule']}`",
                f"- Decision: {row['manualReason']}",
                f"- Matched left form(s): {'; '.join(evidence['leftWitnesses'])}",
                f"- Matched right form(s): {'; '.join(evidence['rightWitnesses'])}",
            ]
        )
        for side_name, contexts in (
            ("Left", row["leftContexts"]),
            ("Right", row["rightContexts"]),
        ):
            for context in contexts[:2]:
                sentence = " ".join(context["sentenceEn"].split())
                if len(sentence) > 550:
                    sentence = sentence[:547] + "..."
                evidence_lines.append(f"- {side_name} evidence `{context['sid']}`: {sentence}")
        evidence_lines.append("")
    evidence_path = OUTPUT / "REGEX_VERIFIED_MERGE_EVIDENCE.md"
    evidence_path.write_text("\n".join(evidence_lines), encoding="utf-8")

    counts = Counter(row["primaryRule"] for row in accepted)
    report = {
        "method": "deterministic regex/string candidate generation plus manual adjudication",
        "embeddingInputsUsed": 0,
        "candidatePool": len(rows),
        "acceptedVerifiedPairs": len(accepted),
        "excludedPairs": len(rows) - len(accepted),
        "excludedContextConflicts": len(REJECT_CONTEXT_CONFLICT),
        "acceptedByRule": dict(counts),
        "sourceClustersModified": False,
        "outputs": {
            "cleanMarkdown": str(clean_path),
            "evidenceMarkdown": str(evidence_path),
            "acceptedCsv": str(csv_path),
            "fullDecisionLog": str(OUTPUT / "regex_candidate_adjudication.jsonl"),
        },
    }
    (OUTPUT / "regex_manual_adjudication_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
